#!/usr/bin/env bash
# ==============================================================================
# download-oscap-stig-deps.sh
#
# Downloads the RPM packages required to run playbook.yml on an air-gapped
# RHEL 8 machine. The playbook was generated by:
#
#   oscap xccdf generate fix \
#     --result-id xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_stig \
#     --fix-type ansible xccdf-results.xml
#
# Analysis of playbook.yml shows it uses only ansible.builtin.* modules
# (no external Ansible collections) and installs exactly four RPM packages:
#   - aide
#   - policycoreutils-python-utils
#   - python3-libselinux
#   - python3-policycoreutils
#
# The air-gapped machine is assumed to already have Ansible and Python 3.12
# installed, so no Ansible, Python runtime, or pip packages are downloaded.
#
# Run this script on an internet-connected RHEL 8 system with an active Red Hat
# subscription (or compatible: CentOS Stream 8, AlmaLinux 8, Rocky Linux 8).
#
# Required repositories:
#   rhel-8-for-x86_64-baseos-rpms
#   rhel-8-for-x86_64-appstream-rpms
#
# Usage:
#   bash download-oscap-stig-deps.sh
#
# Environment variable overrides:
#   OUTPUT_BASE_DIR   Staging directory for downloads  (default: ./oscap-stig-deps)
#   ARCH              CPU architecture                  (default: x86_64)
# ==============================================================================
set -euo pipefail

# ── CONFIGURATION ──────────────────────────────────────────────────────────────
SCRIPT_VERSION="2.0.0"
OUTPUT_BASE_DIR="${OUTPUT_BASE_DIR:-./oscap-stig-deps}"
ARCH="${ARCH:-x86_64}"

# Exact packages the playbook installs via ansible.builtin.package.
# --resolve --alldeps pulls in their full transitive dependency trees so the
# bundle is self-contained on a fresh air-gapped VM.
RPM_PACKAGES=(
    aide
    opensc
    policycoreutils-python-utils
    python3-libselinux
    python3-policycoreutils
)

# createrepo_c is downloaded so the install script can build a local DNF repo
# on the air-gapped machine without any network access.
BOOTSTRAP_PACKAGES=(
    createrepo_c
)

# ── LOGGING ────────────────────────────────────────────────────────────────────
LOG_FILE="${OUTPUT_BASE_DIR}/download.log"

log()  { printf '[%s] [INFO]  %s\n'  "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$LOG_FILE"; }
warn() { printf '[%s] [WARN]  %s\n'  "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$LOG_FILE" >&2; }
die()  { printf '[%s] [ERROR] %s\n'  "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$LOG_FILE" >&2; exit 1; }

# ── PHASE 0: PREFLIGHT ─────────────────────────────────────────────────────────
preflight_checks() {
    log "=== Phase 0: Preflight checks ==="

    if [[ ! -f /etc/redhat-release ]]; then
        die "This script must run on a RHEL/CentOS/AlmaLinux/Rocky 8 system."
    fi
    local os_ver
    os_ver=$(grep -oP '\d+' /etc/redhat-release | head -1)
    if [[ "${os_ver}" != "8" ]]; then
        warn "Expected RHEL 8, detected major version ${os_ver} — proceeding with caution."
    fi

    # dnf-plugins-core provides 'dnf download'
    if ! rpm -q dnf-plugins-core &>/dev/null; then
        log "Installing dnf-plugins-core (required for dnf download)..."
        dnf install -y dnf-plugins-core 2>&1 | tee -a "$LOG_FILE" \
            || die "Failed to install dnf-plugins-core."
    fi

    command -v sha256sum &>/dev/null || die "'sha256sum' not found."
    command -v tar       &>/dev/null || die "'tar' not found."

    # Warn if the standard RHEL 8 subscription repos are not visible
    local required_repos=(
        "rhel-8-for-${ARCH}-baseos-rpms"
        "rhel-8-for-${ARCH}-appstream-rpms"
    )
    for repo in "${required_repos[@]}"; do
        if ! dnf repolist enabled 2>/dev/null | grep -q "$repo"; then
            warn "Repository '${repo}' not in enabled list."
            warn "Enable with: subscription-manager repos --enable ${repo}"
            warn "CentOS Stream 8 / AlmaLinux 8 / Rocky Linux 8 equivalents are also acceptable."
        fi
    done

    # aide is in baseos; policycoreutils-python-utils and python3-* are in appstream
    local avail_kb
    avail_kb=$(df -k "$(dirname "$OUTPUT_BASE_DIR")" 2>/dev/null | awk 'NR==2{print $4}' || echo 0)
    if (( avail_kb > 0 && avail_kb < 512000 )); then
        warn "Low disk space (~$((avail_kb / 1024)) MB); 512 MB+ recommended."
    fi

    log "Preflight checks complete."
}

# ── PHASE 1: DIRECTORY SETUP ───────────────────────────────────────────────────
setup_directories() {
    log "=== Phase 1: Creating output directory ==="
    mkdir -p "${OUTPUT_BASE_DIR}/rpms"
    log "Output directory: ${OUTPUT_BASE_DIR}"
}

# ── PHASE 2: DOWNLOAD RPMs ─────────────────────────────────────────────────────
download_rpms() {
    log "=== Phase 2: Downloading RPMs ==="

    local all_packages=("${RPM_PACKAGES[@]}" "${BOOTSTRAP_PACKAGES[@]}")
    log "Packages: ${all_packages[*]}"

    dnf clean expire-cache 2>&1 | tee -a "$LOG_FILE" || true

    # --resolve  : download all dependencies
    # --alldeps  : include deps even if already installed on this download host,
    #              ensuring the bundle is complete for a fresh air-gapped VM
    dnf download \
        --resolve \
        --alldeps \
        --arch="${ARCH}" \
        --downloaddir="${OUTPUT_BASE_DIR}/rpms" \
        "${all_packages[@]}" \
        2>&1 | tee -a "$LOG_FILE"

    local rpm_count
    rpm_count=$(find "${OUTPUT_BASE_DIR}/rpms" -name '*.rpm' | wc -l)
    log "Downloaded ${rpm_count} RPM file(s)."
    (( rpm_count > 0 )) || die "No RPMs downloaded — check repository access and package names."
}

# ── PHASE 3: GENERATE SHA256 MANIFEST ─────────────────────────────────────────
generate_manifest() {
    log "=== Phase 3: Generating SHA256 manifest ==="

    local manifest="${OUTPUT_BASE_DIR}/manifest.sha256"
    find "${OUTPUT_BASE_DIR}" -type f \
        ! -name 'manifest.sha256' \
        ! -name 'download.log' \
        | sort \
        | xargs sha256sum \
        > "$manifest"

    log "Manifest written ($(wc -l < "$manifest") files): ${manifest}"
}

# ── PHASE 4: WRITE TRANSFER INFO ──────────────────────────────────────────────
write_transfer_info() {
    local rpm_count
    rpm_count=$(find "${OUTPUT_BASE_DIR}/rpms" -name '*.rpm' | wc -l)

    cat > "${OUTPUT_BASE_DIR}/transfer-info.txt" <<EOF
oscap-stig-deps Transfer Package
=================================
Generated   : $(date '+%Y-%m-%d %H:%M:%S %Z')
Script ver. : ${SCRIPT_VERSION}
Source host : $(hostname -f 2>/dev/null || hostname)
Architecture: ${ARCH}

Playbook    : playbook.yml (DISA STIG for RHEL 8, generated by OpenSCAP 1.3.10)
Profile     : xccdf_org.ssgproject.content_profile_stig

Packages required to run the playbook:
$(printf '  - %s\n' "${RPM_PACKAGES[@]}")

Bootstrap package (needed on air-gapped machine to build local repo):
$(printf '  - %s\n' "${BOOTSTRAP_PACKAGES[@]}")

RPM count (including transitive deps): ${rpm_count}

Install instructions: see install-oscap-stig-deps.sh (included in tarball)

NOTE: Ansible and Python 3.12 are assumed to be pre-installed on the
      air-gapped machine. No Ansible collections or pip packages are
      required — the playbook uses only ansible.builtin.* modules.
EOF
    log "Transfer info written."
}

# ── PHASE 5: PACKAGE INTO TARBALL ─────────────────────────────────────────────
package_tarball() {
    log "=== Phase 5: Packaging transfer tarball ==="

    local ts
    ts=$(date '+%Y%m%d-%H%M%S')
    local tarball_name="oscap-stig-deps-${ts}.tar.gz"
    local parent_dir
    parent_dir="$(cd "$(dirname "${OUTPUT_BASE_DIR}")" && pwd)"
    local tarball_path="${parent_dir}/${tarball_name}"

    # Bundle the install script so the tarball is self-contained
    local install_script
    install_script="$(dirname "$(realpath "$0")")/install-oscap-stig-deps.sh"
    if [[ -f "$install_script" ]]; then
        cp "$install_script" "${OUTPUT_BASE_DIR}/install-oscap-stig-deps.sh"
        log "Bundled install-oscap-stig-deps.sh."
    else
        warn "install-oscap-stig-deps.sh not found alongside this script — bundle it manually."
    fi

    tar -czf "$tarball_path" \
        -C "${parent_dir}" \
        "$(basename "${OUTPUT_BASE_DIR}")" \
        2>&1 | tee -a "$LOG_FILE"

    sha256sum "$tarball_path" > "${tarball_path}.sha256"

    log "============================================================"
    log "  Transfer package ready"
    log "  Tarball : ${tarball_path}"
    log "  SHA256  : ${tarball_path}.sha256"
    log ""
    log "  Transfer BOTH files to the air-gapped machine, then:"
    log ""
    log "    # Verify integrity"
    log "    sha256sum -c ${tarball_name}.sha256"
    log ""
    log "    # Extract"
    log "    tar -xzf ${tarball_name}"
    log ""
    log "    # Install (as root)"
    log "    cd oscap-stig-deps"
    log "    sudo bash install-oscap-stig-deps.sh"
    log "============================================================"
}

# ── MAIN ───────────────────────────────────────────────────────────────────────
main() {
    mkdir -p "${OUTPUT_BASE_DIR}"

    log "============================================================"
    log "  OpenSCAP STIG Dependency Downloader v${SCRIPT_VERSION}"
    log "  Targeting: playbook.yml (DISA STIG RHEL 8)"
    log "============================================================"

    preflight_checks
    setup_directories
    download_rpms
    generate_manifest
    write_transfer_info
    package_tarball

    log "=== Download complete. Log: ${LOG_FILE} ==="
}

main "$@"
